[project]
name = "fit-me-up"
version = "0.1.0"
description = ""
authors = [
    {name = "YoonisKim",email = "runheng1209@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=5.2.7,<6.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "pymysql (>=1.1.2,<2.0.0)",
    "sshtunnel (>=0.4.0,<0.5.0)",
    "pillow (>=12.0.0,<13.0.0)",
    "boto3 (>=1.40.75,<2.0.0)",
    "django-storages (>=1.14.6,<2.0.0)",
    "paramiko (<3.0.0)"
]

[tool.poetry]
packages = [{include = "fit_me_up", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"