# Generated by Django 5.2.7 on 2025-11-17 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.JSONField(blank=True, null=True)),
                ('preferred_colors', models.JSONField(blank=True, help_text="['black', 'white']", null=True)),
                ('preferred_fits', models.JSONField(blank=True, help_text="['oversized', 'regular']", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
