# Generated by Django 5.2.7 on 2025-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrityanalysis',
            old_name='body_type',
            new_name='body_shape',
        ),
        migrations.RenameField(
            model_name='celebrityanalysis',
            old_name='feature_vector',
            new_name='vector',
        ),
    ]
