# Generated by Django 5.2.7 on 2025-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0002_rename_body_type_celebrityanalysis_body_shape_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrity',
            old_name='image_url',
            new_name='body_image_url',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='face_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
