# Generated by Django 5.2.7 on 2025-11-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='is_active',
        ),
    ]
