# Generated by Django 5.2.7 on 2025-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='styles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
