# Generated by Django 5.2.7 on 2025-11-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('body_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.userimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
