# Generated by Django 5.2.7 on 2025-11-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userimageanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('body_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('vector', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_analysis', to='accounts.userimage')),
                ('face_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_analysis', to='accounts.userimage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserImageAnalysis',
        ),
    ]
